Assignment Session 7 (Filter)
jhnwendell02/ASPNetCoreMasters pull request #9
Opened 2021-10-09 11:41 UTC by jhnwendell02

Hi Sir @ranton @jegtugado @juliuscnicolas @kevinatgithub here is my homework for session 7. Thank you :)

2021-10-09 12:33 UTC, jegtugado requested changes
Hi sir. minor change needed

2021-10-09 12:33 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/Controllers/ItemsController.cs
> +        [EnsureItemIdExistFilterAttribute]
Hi sir please apply the filter on the controller scope

2021-10-09 12:33 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/Filters/EnsureItemIdExistFilter.cs
> +            if (isExist == null)
please handle scenarios where the action doesn't need to ensure an item exists (no itemId parameter)

2021-10-09 12:33 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/Filters/ExecutionTimeFilter.cs
> +            context.HttpContext.Items["StartTime"] = DateTime.UtcNow;
excellent approach to prevent race conditions!

2021-10-09 12:33 UTC, jegtugado commented on ASPNetCoreMastersTodoList.Api/Filters/ExecutionTimeFilter.cs
> +            context.HttpContext.Items["StartTime"] = DateTime.UtcNow;
next time, we recommend using a StopWatch for easier time elapsed tracking

2021-10-10 07:45 UTC, kevinatgithub commented on ASPNetCoreMastersTodoList.Api/Filters/ExecutionTimeFilter.cs
> +            context.HttpContext.Items["StartTime"] = DateTime.UtcNow;
May I ask, why are you assigning value to StartTime again here? Thanks

2021-10-15 05:59 UTC, kevinatgithub approved these changes

2021-10-15 05:59 UTC, merged